export const STATION = {
  name: 'Pan Africa Radio24',
  tagline: 'Africa Official Radio Station',
  footerText: 'v1.0.0 - Powered by Streamo Core',
  logo: require('../../assets/icon.png'),
  remoteConfigUrl: 'https://api.streamo.ng/api/mobile/v1/global/config',
  streamUrl: '',
  nowPlayingUrl: '',
  scheduleTodayUrl: '',
  scheduleWeekUrl: '',
  scheduleEventsUrl: '',
  listenerMapUrl: '',
  countryStatsUrl: '',
  scheduleUrl: '',
  apiBase: '',
  stationId: '',
  apiKey: '',
  email: '',
  phone: '',
  whatsapp: '',
  website: '',
  aboutText: '',
  primary: '#4A9EFF',
  accent: '#2ECC71',
  enableNotifications: true,
  enableSchedule: true,
  enablePodcasts: false,
  metadataRefreshMs: 15000,
  reconnectMaxDelayMs: 10000,
  reconnectBackoff: 1.5,
};
